### ISSUE TITLE
Overlapping text in debug menu

### ISSUE THREAD

**Issue by gioporta** [NationCraft/NationCraft-Pack#1]
When clicking F3 to open the debug menu, there is a line of text that overlaps another, therefore making the entire line unreadable.

**Comment by GiovanniPorta** [comment]
Possibly Hunger Overhaul.

**Comment by gioporta** [comment]
Possibly AppleCore.

https://github.com/GiovanniPorta/NationCraft-Pack/blob/master/src/config/AppleCore.cfg#L13

**Comment by littledan45** [comment]
B:show.food.stats.in.debug.overlay=false
does fix a few lines in the left top corner where you see the fps but there stays some overlapping in the right top corner.

If you add Journey Map it will also overlap the second line in F3 but at least you will be able to see the FPS.

**Comment by gioporta** [comment]
AppleCore was definitely the mod that was overlapping text in the top left.

FastCraft seems to be overlapping in the top right.

**Comment by gioporta** [comment]
Tested further.

It appears B3M is the culprit. The other mods such as FastCraft, AppleCore, JourneyMap, etc all render correctly on the debug screen when B3M isn't installed. However, when B3M is installed, they all end up overlapping. I suspect B3M is changing the debug screen render code.

**Comment by littledan45** [comment]
Yea I was thinking that also that their would be 1 mod screwing up the the rendering positions

**Comment by gioporta** [comment]
Fixed in B3M 1.7.9-07
See [forum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289314-1-4-7-1-8-9-1-9-vrashenie-zemli-majnkraftskaya) for changelog
