### ISSUE TITLE
Request adding mod OcGlasses

### ISSUE THREAD

**Issue by littledan45** [NationCraft/NationCraft-Pack#15]
https://github.com/StarChasers/OCGlasses

Can we add this mod

**Comment by gioporta** [comment]
OpenPeripheral already has terminal glasses that work with CC/OC. Is there any point in adding this?

**Comment by littledan45** [comment]
Oh I must be doing something wrong I couldn't get the openperipheral terminal to work with Oc

**Comment by gioporta** [comment]
You might need to connect your Terminal Glasses Bridge to an OC adapter if it doesn't work when connected directly to your computer.

If the Terminal Glasses don't work, then they at least used to. See https://github.com/MightyPirates/OpenComputers/issues/293

**Comment by littledan45** [comment]
Will try it tomorrow and I'll let you know

**Comment by littledan45** [comment]
I got Openperipherals to work so I'm ok with that one
