### ISSUE TITLE
Flower Heads not rendering

### ISSUE THREAD

**Issue by littledan45** [NationCraft/NationCraft-Pack#16]
All vanilla flowers are not rendering the heads, not even in my inventory

**Comment by gioporta** [comment]
Is this issue present on every world or just one?

**Comment by littledan45** [comment]
It does it on all new worlds made with pre6. I think it was fun that also mentioned that on skype

**Comment by gioporta** [comment]
Can you give yourself the Seasons Watch (an item) on each world it's doing it and see if they're all the same season? If so, just post what season it is.

**Comment by littledan45** [comment]
What terrain do you select on the server

**Comment by gioporta** [comment]
Shouldn't matter. But we use ATG.

**Comment by littledan45** [comment]
Ok it happens to all worlds created with default gen. ATG is fine though
