### ISSUE TITLE
Growthcraft rice pad and Agricraft water pad conflict

### ISSUE THREAD

**Issue by aflame13** [NationCraft/NationCraft-Pack#20]
By default, both are made the same way (left click on tilled soil with shovel) but the Agricraft water pad takes priority so it's impossible to make Growthcraft rice pads. Issue can be fixed by changing Agricraft config to only make water pads while sneaking. Default for that config is false.

**Comment by gioporta** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.7/issues/150
