### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by gioporta** [NationCraft/NationCraft-Pack#6]
Find ways to improve FPS client-side.

**Comment by gioporta** [comment]
https://github.com/GiovanniPorta/NationCraft-Pack/blob/master/src/config/Galacticraft/core.conf#L44
Setting to true.

**Comment by GiovanniPorta** [comment]
[4a40790](https://github.com/GiovanniPorta/NationCraft-Pack/commit/4a407902296578a6e9bbce3388feece007ddedbd)

**Comment by gioporta** [comment]
DecoCraft allegedly uses 600MB of RAM, will be removing. Can be re-added later if needed.

[Reference](http://forum.feed-the-beast.com/threads/guide-how-to-run-infinity-evolved-with-1-0gb-ram-allocation.149222/)
