### ISSUE TITLE
Modpack launcher repeating download bug

### ISSUE THREAD

**Issue by littledan45** [NationCraft/NationCraft-Pack#8]
Launcher 0.9.1 on Linux keeps downloading http://files.inpureprojects.info/libs/commons-compress-1.8.1.jar and a few more with every launch.

might not be a bug?

**Comment by littledan45** [comment]
Ok it looks like its getting a connection time out so it could be their problem

**Comment by gioporta** [comment]
His website is down, and it's trying to pull those files every time. See [here](https://github.com/INpureProjects/INpureCore/issues/21)

Need to manually add the files to the pack so it doesn't try to download them.
