### ISSUE TITLE
Morpeus player sleeping ratio

### ISSUE THREAD

**Issue by littledan45** [NationCraft/NationCraft-Pack#9]
https://github.com/GiovanniPorta/NationCraft-Pack/blob/master/src/config/Morpheus.cfg

I:SleeperPerc=100

Did you plan on leaving it like this? if I am correct this is the percentage of players that have to be sleeping for it to turn morning right?

**Comment by gioporta** [comment]
I wasn't sure what I was going to set it to, perhaps 75%. What do you have in mind?

And yes that's correct.

**Comment by littledan45** [comment]
I usually had it at 50% so that if you had 2 players playing only 1 had to go to sleep
